### ISSUE TITLE
LDAP.AddUSerToGroups - UserExistsAction.Skip is not working 

### ISSUE THREAD

**Issue by PhilipHakans** [FrendsPlatform/Frends.LDAP#16]
Currently if you set "Skip" the task will fail and return a System.Exception, not a Result with Success = false. This is because the code is currently checking for "Attribute Or Value Exists" as the exception message but it appears that the actual error message we want to be checking for is "Entry Already Exists". 

I tried to create a pull request with this fix but I am not authorized to do so. 

Change row 45 of AddUserToGroups.cs from:
(ex.Message.Equals("Attribute Or Value Exists") && input.UserExistsAction.Equals(UserExistsAction.Skip)) 
To
(ex.Message.Equals("Entry Already Exists") && input.UserExistsAction.Equals(UserExistsAction.Skip)) 
And I think it should work as planned.

**Comment by RikuVirtanen** [comment]
@PhilipHakans I tested this against our docker container test setup and docker did actually return the "Attribute Or Value Exists" message. This indicates that there can be multiple different messages coming as a response which should be taken care of in the error handler. I will try to make the change in a different way. One option would be to check if the user exists in the group before trying to add it. Then we don't have to check for error responses at all because it not usually the best practice.

**Comment by PhilipHakans** [comment]
@RikuVirtanen must be something different in our environments. Not super surprising either to be honest. What's important here though is a better way to handle this, yes. I worked around this in our environment with a catch in FRENDS but a consistent behaviour for UserExistsAction.Skip would obviously be preferable. 

Thank you for your time!

**Comment by RikuVirtanen** [comment]
@PhilipHakans new version is now done and will be released very soon where this issue is now fixed by adding check for the user in the group instead of checking the error codes and messages.
